### ISSUE TITLE
Create database before migration if it doesn't exist

### ISSUE THREAD

**Issue by leoi11** [justinforce/apm_helpers#25]
On a new app, when running `apm update`, if the database doesn't exist for the new app/engine, it continues with errors after trying to migrate.

```/Users/leolei/src/apm_bundle/apps/messenger: Bundling...
/Users/leolei/src/apm_bundle/apps/messenger: Migrating env test...
/Users/leolei/src/apm_bundle/apps/messenger: Migrating env development...
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown database 'messenger_test': USE messenger_test
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown database 'messenger_development': USE messenger_development
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:127:in `select_database'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:103:in `rescue in hijack_database!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:88:in `hijack_database!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:66:in `account_name='
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:11:in `establish_connection'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/railtie.rb:127:in `block (2 levels) in <class:Railtie>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/Users/leolei/src/apm_bundle/apps/messenger/config/environment.rb:5:in `<top (required)>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/Users/leolei/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/leolei/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:127:in `select_database'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:103:in `rescue in hijack_database!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:88:in `hijack_database!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:66:in `account_name='
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/af_runtime-6.12.0/lib/af_runtime/models/hijack.rb:11:in `establish_connection'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/railtie.rb:127:in `block (2 levels) in <class:Railtie>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activerecord-4.1.12/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/Users/leolei/src/apm_bundle/apps/messenger/config/environment.rb:5:in `<top (required)>'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/Users/leolei/.rvm/gems/ruby-2.2.3/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/Users/leolei/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/leolei/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: Unknown database 'messenger_test'
Mysql2::Error: Unknown database 'messenger_development'```

**Comment by justinforce** [comment]
Again, I use a separate script for this. My idea was, "I'll develop these little one off things, and when I like them I'll merge them into apm_helpers." But I haven't gotten around to merging [mkdbs](https://github.com/justinforce/dotfiles/blob/master/files/bin/mkdbs) yet. If you're interested in trying it out, I welcome any feedback. Here's the help text from mkdbs to give you an idea what it does:

```
mkdbs: Set up all of your APM Bundle databases

Usage: mkdbs [OPTIONS]

OPTIONS:
  -M  Don't migrate databases (rake db:migrate)
  -P  No parallelism. Do everything in serial. SLOWER.
  -S  No checking out schemas afterward. (git ls \*/schema.rb | xargs git checkout)
  -c  Create databases (rake db:create)
  -d  Drop databases before creating (rake db:drop)
  -f  Load fixtures (rake db:fixtures:load)
  -h  Show this help

(Supports debug output thusly: DEBUG_APM=1 mkdbs)
```
